### ISSUE TITLE
Memory Benchmarks

### ISSUE THREAD

**Issue by aiqc** [fireducks-dev/fireducks#28]
A major constraint of single-node computation is the amount of available memory.

It would be nice to see the same benchmarks against competing tools as memory pressure line charts over time.

Given that fireducks uses pointers rather than in-place transformations, how does this impact memory utilization?

> FireDucks actually doesn’t support in-place operations in true sense, since it assumes all the data instances are immutable in nature (to improve performance). Whenever an in-place operation on a column is performed, e.g. df["A"] += 2, it allocates a new memory for that column to write the result of the operation and modifies the data pointer as shown below to make it look like an in-place operation.
>
> https://fireducks-dev.github.io/docs/user-guide/04-compatibility/

My use case = I have an AWS Batch job that uses pandas and consumes 20GB RAM. If I migrate to fireducks, do I need to change my cloud instance type to increase my memory?

---

P.S. does `inplace=True` result in either an error, a warning, or is it silently ignored?

**Comment by qsourav** [comment]
Hi @aiqc,

Appreciate your interest in FireDucks. Let me answer your queries one-by-one.

> A major constraint of single-node performance is the amount of available memory.

Agreed. Please find below some points related to memory optimization in FireDucks.
- The internal data structures for DataFrame/Series are backed by apache arrow. So you might expect better memory usage, especially when dealing with non-numeric columns like string, boolean etc.

- The JIT compiler attempts to perform several optimization before executing your program (by loading only required columns, by performing early filtration etc. before performing computatinal expensive operations like join, groupby, sort etc). So, you may expect huge gain in terms of computational memory and execution time when switching to FireDucks.

For example, here is a notebook explaining projection related optimization:
https://colab.research.google.com/drive/1qVda3K2GiWqZvarkRxwHWwSazBIxeLeM?usp=sharing#scrollTo=IvCMs4fh5wij

You can see the native approach takes around 3 GB, whereas hand-optimized approach takes around 0.1 GB when running with native pandas.

Here is another notebook with FireDucks:
https://colab.research.google.com/drive/1Ze7iUUeX7SssPpbIuGzhzBFDBD7gOkpO?usp=sharing

You can see both the native approach and hand-optimized approach takes ariound 0.1 GB (due to internal optimization in FireDucks).

- We are also extending such optimization during the data loading stage to support larger-than-memory dataset.

> Given that fireducks uses pointers rather than in-place transformations, how does this impact memory utilization?
Due to efficient implementation using shared-pointer, we tried to avoid unnecessary data copies during the dataframe related operations. So, you should definitely expect better memory usage when switching to FireDucks.

> My use case = I have an AWS Batch job that uses pandas and consumes 20GB RAM. If I migrate to fireducks, do I need to change my cloud instance type to increase my memory?

Ideally you do not need to make any changes, but sometime due to internal fallback to pandas (data copy from FireDucks backend to pandas) there is increase in memory consumption for some unsupported methods. In case you experience increase in memory, [please check](https://fireducks-dev.github.io/docs/user-guide/tips/#avoid-fallback) the if there are any methods that are fallbacking to pandas. We are removing expensive fallbacks by supporting the methods (or some parameter of already supported methods) in every week's release. In case you find any, please feel free to report us, such that we can support them on priority.

> P.S. does inplace=True result in either an error, a warning, or is it silently ignored?
"inplace=True" will work as per expectation for your program, although the internal working will not be in-place in true sense. So, there will be no error or warning. 

Please let me know in case you have any further query or confusion at any point.

Thanks and Regards,
Sourav

**Comment by qsourav** [comment]
> https://fireducks-dev.github.io/posts/lazy_execution_offering_part1/
It is to inform you that since FireDucks 1.1.1, we have extended the optimization support .(early projection of the required columns etc.) during data loading stage for data stored in columnar formats like parquet, csv etc. You may like to check the [article](https://fireducks-dev.github.io/posts/lazy_execution_offering_part1/) for more details.
